### ISSUE TITLE
Battery life during deep sleep and HA integration. 

### ISSUE THREAD

**Issue by cbrollin** [jhansche/ha-birdbuddy#21]
My bird buddy has now been going into deep sleep during the night, as it is designed to do. 

Thanks to this integration, I can see the battery life during that time, and I am basically seeing no change in behavior compared to normal operation. Status timeline shows purple as ready, and light blue as sleeping. Time periods for the two graphs are the same. 

![06A1DD22-6D50-48C2-9648-1337B7179933](https://user-images.githubusercontent.com/83191359/211966277-31f2eba0-ea49-4445-9e62-bf6fad915a50.jpeg)
![1572FB1A-611E-41C8-88DE-EE41AC47040B](https://user-images.githubusercontent.com/83191359/211966279-75b9096f-bcdc-4437-854a-ba0c1d845a89.jpeg)

I am wondering if this integration is excessively polling (even if it is every 5 min) during the night, and reducing the battery life. Or do we think the Bird Buddy app polls at the same rate regardless? I am trying to figure out how to test this. 

Maybe we can restrict polling based on sunrise/sunset of the feeder location (like how the feeder works), or restrict polling for a certain time period following the first deep sleep status message.

**Comment by jhansche** [comment]
Really? I definitely see a difference in my battery usage, since they turned on deep sleep overnight. In my graphs you can see a very clear change of trend starting Jan 5-6, when they enabled sleeping:

![Screenshot_20230111-223021](https://user-images.githubusercontent.com/99272/211969573-346f1b8e-b792-4ec7-8fa5-7691011d0c0c.png)

![Screenshot_20230111-222840](https://user-images.githubusercontent.com/99272/211969545-f64e83a1-fcf0-4f3a-8e19-78661dd66899.png)

I am very nearly certain that us polling the GraphQL API does not do anything to wake the feeder. I say that because the API responses are pretty fast, and if it had to wait for a response from the feeder, it would be much slower and more erratic. Also if it were keeping it from sleeping, then it would not remain in deep sleep state overnight, but it does.

I believe the only thing that would cause it to wake up and prevent it from sleeping, would be if we instructed it to enter streaming mode, which even when you do that from the app, it can take up to 2 minutes before the streaming actually starts. It has that potential delay, because it just sets a flag on the server side, and waits for the feeder to check in and see the flag is set, before the feeder actually starts streaming the camera feed. If hitting the API alone would wake the feeder, then it wouldn't have that long of a delay before starting the stream.

**Comment by cbrollin** [comment]
Huh. Ok. Well your device and data seem to act how I would expect. Maybe I need to reset, or reboot my bird buddy. I will try that out.

**Comment by jhansche** [comment]
From the earlier parts of the 30+ day maroon graph, you can see that I used to have to charge it every 2-4 days. But this week it lasted from Jan 4-11, just about doubling the battery life.

Also see these shots from Jan 3-6. I had started experimenting with putting it off-grid, which actually did nothing for preserving battery. The next day I started seeing deep sleep state, and that actually did have a noticeable impact:
![Screenshot_20230111-224652](https://user-images.githubusercontent.com/99272/211971298-92e7ad27-eb7e-43ee-ae94-4d94b09fb4a7.png)
![Screenshot_20230111-224600](https://user-images.githubusercontent.com/99272/211971313-4d24fc9b-d692-4ba6-9ac6-7e54b9999ce7.png)

**Comment by jhansche** [comment]
Another thing to consider might be the placement of your feeder -- for example, the support site mentions things like a waving flag near the FOV of the camera, or if your feeder is hanging, it might be moving if it's windy. Now, that article might be outdated since the change to enable sleep mode, since there's no reason it should wake up from a flag in the frame. But just something to consider.

I think your idea of trying to power cycle it could be a good first step, and also make sure you're on the latest firmware (1.1.0).

If you do suspect the integration still, you can try disabling the integration in HA for a day, or even a few hours, and then see if the battery trend looks any different. Of course you wouldn't see the graph during that time, but you'll be able to see the trend from before and after. If the graph looks like it would connect on the same trend, then we can rule out the integration causing it.

**Comment by jhansche** [comment]
@cbrollin any update here? Were you able to try a test with the integration disabled? Or did you try a soft reset?

**Comment by cbrollin** [comment]
I tried a power cycle, and that seemed to fix the problem. I am seeing the appropriate behavior now. 
![49B4CB77-F20E-481A-B26C-820C9EF90DE6](https://user-images.githubusercontent.com/83191359/212577289-e000197f-2338-4a63-9a8f-ed05e5ccedf4.jpeg)
