### ISSUE TITLE
Installation fails with error.

### ISSUE THREAD

**Issue by rklueber** [jhansche/ha-birdbuddy#3]
Hello,

got my bird buddy yesterday. Vivid HA user here ,-). Loved this and had to try it out.

Home Assistant 2022.12.8
Supervisor 2022.12.1
Operating System 9.4
Frontend 20221213.1 - latest

Added the repo to HACS ... installed the integration via HACS ... rebooted HA ... added the integration via settings ... and got this.

Fehler
Der Konfigurationsfluss konnte nicht geladen werden: {"message":"Invalid handler specified"}

Any help apretiated..

**Comment by jhansche** [comment]
Is there any additional stack trace to go with that error?

When you installed it in HACS, what version did you select (or were you given the option)? You'll see the version when you click on the Bird Buddy item in HACS, it will be in the top-left chip with the "box" icon. You'll want to make sure that says `v0.0.4`. If it shows a hash like `ea798ff`, that means it got installed from a branch, and the branch installation method is not guaranteed to work, because it includes in-development work that won't be available until the associated pybirdbuddy library gets updated on PyPI.

If it's a hash, you can switch to a tagged version by clicking the 3-dots overflow menu on the top-right in the Bird Buddy repo screen in HACS, go to Redownload, and then for "Select version", choose version `v0.0.4`.

If it didn't give you the option to select a version at first, but still picked the branch instead, then I might need to promote a version to make HACS pick a more intelligent default. All versions are currently in "Prerelease" mode, which means ordinarily you would need to select the "Beta" checkbox in order to see them.  So it's possible that because there is no full (non-prerelease) version yet, HACS may be defaulting to the `main` branch.

Let me know if that helps.

**Comment by jhansche** [comment]
I've promoted `v0.0.4` tag to a full release - so hopefully that will cause HACS to select it by default in the future. I'm curious to know if that's the problem.

There was an issue #1 opened yesterday where their HACS repo version shows a git hash instead of a tagged version like I was expecting - except their installation worked. But since then I've pushed additional code to that main branch, which is not going to work until the pybirdbuddy library gets updated in PyPI.

**Comment by jhansche** [comment]
I've also just released `v0.0.5`, as a pre-release. `v0.0.4` is still tagged as the "latest" release, so new installations from HACS should choose that version first.

To get other versions, you should select the Beta checkbox in the Redownload dialog, and select a tagged version.

Please let me know if selecting a tagged version (v0.0.4 or v0.0.5) works for you.

**Comment by rklueber** [comment]
Works. I tried v0.0.4 some minutes ago. Works now. I can see battery entity. Rest was deactivated. I activated them and now can see all 4 entities. Thanky you for your support. Happy to test new stuff as soon as the bird buddy is outside. Currently its in a parcel ... for my wifies birthday next week ,-).

**Comment by jhansche** [comment]
Great! Glad to see it's working now.

And good to know that HACS works this way (this is my first custom component, so still getting used to it).

I'll take a look at how other HACS projects handle the "in development" stage, where it requires the PyPI library to be updated first, before it can be available in HA installs. Particularly when changes are allowed to remain "parked" in a branch, before it gets finalized and release as a tag.

It could be as simple as having all-prerelease versions which caused HACS to default to the `main` branch instead of defaulting to the latest tag version. And if that's the case, then it's easy enough to fix - I'll just make sure not to keep all versions marked pre-release.

Thanks for the info, and hope your wife enjoys it :)
