### ISSUE TITLE
No recent visitors after 2024.5 update

### ISSUE THREAD

**Issue by AuroreVgn** [jhansche/ha-birdbuddy#83]
Hi!

After an upgrade to **2024.5**, "Recent Visitor" doesn't work. To be more specific:  "sensor.recent_visitor" sensor was "Unavailable" despite is "Enable" in the settings as you can show bellow.
Please note that I am running the last version of BB integration: 0.0.19 (with the tricks mentioned in [this issue](https://github.com/jhansche/ha-birdbuddy/issues/82))

![image](https://github.com/jhansche/ha-birdbuddy/assets/74768535/ea932d01-1397-4e49-92d2-84436b3bb987)
![image](https://github.com/jhansche/ha-birdbuddy/assets/74768535/0d1d94c0-7b29-48ec-a1c2-13865e071d01)

**Comment by jhansche** [comment]
I just updated to 5.1, and I'm not seeing either issue, this one or #82. I didn't have to patch my langcodes version, and my recent visitor entity is working correctly. 

Do you have any `birdbuddy` related warnings or errors in the logs? 

I'm the BB app, do you see any recent visitors there - especially in the Saved view? Sometimes after a restart of HA you might have to wait until the next postcard arrives, since it will populate from new postcards. It does also try to populate from the last saved postcard in the feed as well, but that's only a best-effort attempt.

**Comment by AuroreVgn** [comment]
I have a look at the logs and I only have the following ones:

<img width="637" alt="image" src="https://github.com/jhansche/ha-birdbuddy/assets/74768535/c141ce12-0d86-46fb-8892-3949161870f6">

In BB app, I can seen recent visitors today.

**Comment by jhansche** [comment]
That error looks promising. What's the actual log?

**Comment by AuroreVgn** [comment]
I click on the errror log mentionned bellow and I have the following details:

```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:580
integration: Sensor (documentation, issues)
First occurred: May 3, 2024 at 20:05:38 (3 occurrences)
Last logged: 17:26:40

Error adding entity sensor.etourmi_recent_visitor for domain sensor with platform birdbuddy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 580, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 892, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1358, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/birdbuddy/sensor.py", line 148, in async_added_to_hass
    await self._update_latest_visitor()
  File "/config/custom_components/birdbuddy/sensor.py", line 216, in _update_latest_visitor
    medias := [
              ^
TypeError: 'NoneType' object is not iterable
```

**Comment by jhansche** [comment]
Yeah if the sensor platform didn't load, then it likely wouldn't have finished the rest of the sensors either. I'll take a look at that your, thanks for reporting.

**Comment by jhansche** [comment]
You can try installing the version in the PR branch, with this service call:
```yaml
service: update.install
target:
  entity_id: update.bird_buddy_update
data:
  version: pr/fix-83
```
Afterwards it will ask you to restart HA to finish the install. Note it will start saying that there's a newer version (v0.0.19), but that's just because this PR branch isn't released yet.

Let me know if a) your recent visitors entity starts working again, and/or b) the rest of the sensors start working again.

**Comment by AuroreVgn** [comment]
I tried to "update" to pr/fix-38 by using your service call under the "Developer tools" menu tab "services" and I still am in 0.0.19. I also tried to pu the code you provide in configuration.yaml or in a script ("Automation" menu then "Scripts" tab) without success. 
I am not very sure this is the good way to use a service call. Could ou please tell me what is the right way to do this?

**Comment by jhansche** [comment]
Doing it from the developer tools screen is the correct place:

![Screenshot 2024-05-05 at 1 50 28 PM](https://github.com/jhansche/ha-birdbuddy/assets/99272/60b0bebe-961c-4639-aa0b-b058f67bb5df)


After running the service, you'll go back to the Settings menu, and there will be 2 Bird Buddy notifications at the top: one telling you to restart HA, and the other telling you that there is an update available:

![Screenshot 2024-05-05 at 1 48 19 PM](https://github.com/jhansche/ha-birdbuddy/assets/99272/d74ac8e7-d993-4d05-9fd2-56dc51d727df)

You need to *ignore* the update line, because that will undo the PR version. You'll note that in the dialog - it's trying to replace the `pr/fix-83` version with `v0.0.19`, which is NOT what you want:
![Screenshot 2024-05-05 at 1 46 46 PM](https://github.com/jhansche/ha-birdbuddy/assets/99272/024a34d1-3c4c-4d4e-b1e1-0a7d70cd5e56)

But you do have to click the `Restart required` repair, and actually restart HA. After it restarts, it will continue showing the available update to v0.0.19, but you must continue to ignore it. If you install that, it will remove the PR fix.

**Comment by AuroreVgn** [comment]
Thank you!
I think I still have an issue to run the service install :-( I can see this warning in logs :
<img width="589" alt="image" src="https://github.com/jhansche/ha-birdbuddy/assets/74768535/0641a43d-5bc8-4825-bc70-43b2c4195e66">

**Comment by jhansche** [comment]
OK, that means the HACS update entity isn't right.

When you go to Settings > Devices & Services > Entities tab, and search for "bird buddy", you should see an Update entity owned by integration `HACS`. That entity is the one you need to use in the service call.
![Screenshot 2024-05-05 at 2 36 19 PM](https://github.com/jhansche/ha-birdbuddy/assets/99272/c7c2e34e-1f25-457a-9382-50520a37cc22)

Or in the Dev Tools Service screen, click the `Go to UI Mode` button in the bottom left, and choose the correct entity from the "Choose Entity" list. Pick the one that DOES NOT have the name of your BB and "Firmware" in the name, that is different, because that's the one to install a BB firmware update. You want the one that is just named "Bird Buddy Update":
![Screenshot 2024-05-05 at 2 38 09 PM](https://github.com/jhansche/ha-birdbuddy/assets/99272/2bf849f9-4bc9-4fa8-a19a-f333eb4eda70)

**Comment by AuroreVgn** [comment]
I don't have any entities related to bird buddy and own by HACS :-(

<img width="1402" alt="image" src="https://github.com/jhansche/ha-birdbuddy/assets/74768535/c5debc0f-a6b2-450c-a2b0-472319aab367">

**Comment by jhansche** [comment]
Did you install the BB integration via HACS, or installed manually?
Do you have _any_ `update.*` entities owned by HACS?

I wonder if this might be an Experimental feature of HACS 🤔  If you go to the [HACS integration page](https://my.home-assistant.io/redirect/integration/?domain=hacs) and then click the "Configure" button, do you have `Enable experimental features` checked?

**Comment by AuroreVgn** [comment]
I have installed BB integration (and all other one) with HACS and I have no 'update' entities at all.

Yeeahhhh! By activating experimental featured, I have a lot of 'update' entities!! 

I can follow your tutorial above!

**Comment by AuroreVgn** [comment]
I did it.

Good news! I now have the recent visitor working (and it seems I have some history): 
<img width="556" alt="image" src="https://github.com/jhansche/ha-birdbuddy/assets/74768535/654fef3e-f6da-416c-80e6-ec5872889452">

I can't tell you right now if the sensors are updating without manual reload but it seems not.
I will let you now tomorrow after the night (Paris time).

**Comment by jhansche** [comment]
If it's nighttime, and the BB is in sleep mode, then move off the sensors will update until it's online again. 

If it's not in sleep mode and you're also not seeing other entities update still, then there might be another warning or error in your logs?

**Comment by AuroreVgn** [comment]
After the night, it seems that all sensors are updating alone :-)

Battery:
<img width="542" alt="image" src="https://github.com/jhansche/ha-birdbuddy/assets/74768535/a03f345f-b40f-4dc4-9123-63fce027ace2">

State:
<img width="563" alt="image" src="https://github.com/jhansche/ha-birdbuddy/assets/74768535/959213d7-3769-4152-8ccd-ee5fdfc318f1">

Your fix is working!

**Comment by jhansche** [comment]
Great, thank you for testing. This will be addressed in the next release.
